### ISSUE TITLE
UltraHDR

### ISSUE THREAD

**Issue by mrdoob** [ULuIQ12/webgpu-isoline-geometry#1]
You could save 5MB+ by [converting](https://gainmap-creator.monogrid.com/) the HDR to UltraHDR and using [UltraHDRLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/UltraHDRLoader.js).

![Screenshot 2024-08-06 at 3 53 37 PM](https://github.com/user-attachments/assets/e6298ef3-3214-4c40-868d-3f2d79495a24)

[table_mountain_2_puresky_2k.hdr.jpg](https://github.com/user-attachments/assets/581415a7-bd92-425f-acc1-edfbbd8c681a)

**Comment by mrdoob** [comment]
Same thing in [furball](https://ulucode.com/random/webgputests/furball/).

![Screenshot 2024-08-06 at 4 00 55 PM](https://github.com/user-attachments/assets/6f2f9ea8-858c-453f-91cf-757be7dc7e03)

[wide_street_01_2k.hdr.jpg](https://github.com/user-attachments/assets/123acbbd-d221-4330-9039-4b47622b7b33)

**Comment by ULuIQ12** [comment]
Wow, that's crazy!
Done! Thx for the tip :)
